{
 "title": "Monitoring - Perfmon Counters - Quest Softwares",
 "description": "This dashboard is designed to match the counters mentioned in document published by QUEST SOFTWARE on \"SQL Server Perfmon Counters of Interest\"",
 "tags": [
  "SqlServer",
  "MSSQL",
  "Performance-Counter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "select server_name\nfrom (values ('MSI')\n\t\t\t,('SQL-A')\n\t ) as servers (server_name);"
   }
  ]
 },
 "panels": [
  {
   "title": "OS Memory & Paging Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - Available Mbytes",
     "type": "graph",
     "description": "Unused physical memory (not page file).\nShould be greater than 2 GB",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect dbo.local2utc(collection_time) as time, (available_physical_memory_kb*1.0)/1024 as [Available Memory]\nfrom [dbo].[dm_os_sys_memory]\nwhere 1 = 1\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\n--and pc.server_name = @server_name\norder by collection_time asc;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Memory - Pages Input/Sec, Pages/Sec",
     "type": "graph",
     "description": "Pages Input/Sec\n-- Should be less than 10\n-- Reads from hard disk per second to resolve\nhard pages.\n\nPages/Sec\nOften referenced in older documentation.\nUseful only in combination with Pages\nInput/Sec, %Usage, %Usage Peak.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect dbo.local2utc(pc.collection_time) as time, pc.counter_name, CEILING(pc.cntr_value) as cntr_value\nfrom dbo.dm_os_performance_counters_nonsql as pc\nwhere 1 = 1\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\nand pc.[object_name] = 'Memory'\nand pc.counter_name in ('Pages Input/Sec','Pages/Sec')\norder by pc.collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Paging File Usage",
     "type": "graph",
     "description": "Paging File: %Usage\n-- Should be less than 70%\n-- Amount of Page File in use, which indicates\nthe server is substituting disk space for\nmemory.\n\nPaging File: %Usage Peak\n-- Should be less than 70%\n-- Highest %Usage metric since the last time\nthe server was restarted.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect dbo.local2utc(pc.collection_time) as time, pc.counter_name, CEILING(pc.cntr_value) as cntr_value\nfrom dbo.dm_os_performance_counters_nonsql as pc\nwhere 1 = 1\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\nand pc.[object_name] = 'Paging File'\nand pc.counter_name in ('% Usage','% Usage Peak')\norder by collection_time asc;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "OS CPU & Processor Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "%Processor Time (SqlServer)",
     "type": "graph",
     "description": "< 80%. \nPercentage of processor time spent on SQL\nServer process threads.You may also wish\nto investigate other Process (sqlservr) such\nas Private Bytes, Virtual Bytes, Working Set,\netc to get a fuller understanding of how\nSQL Server allocates certain segments of\nmemory. Usually, these auxiliary counters\nprovide contextual information and are not\nnecessary for troubleshooting.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect /* Grafana => CPU */\n\t\tdbo.local2utc(collection_time) as time,\n\t\tmetric COLLATE SQL_Latin1_General_CP1_CI_AS,\n\t\t[value]\nfrom (\tselect\tcollection_time,\n\t\t\t\tsystem_cpu_utilization as [% Processor Time (os)],\n\t\t\t\tsql_cpu_utilization as [% Processor Time (sqlservr)]\n\t\tfrom dbo.dm_os_ring_buffers\n\t\twhere 1 = 1\n\t\t--and collection_time >= DATEADD(MINUTE,-120,getdate())\n\t\tand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\n\t ) as up\nUNPIVOT ([value] FOR metric IN ([% Processor Time (os)],[% Processor Time (sqlservr)])) AS UnPvt\n--\nUNION ALL\n--\nselect  dbo.local2utc(pc.collection_time) as time\n\t\t,metric = case when pc.[object_name] = 'Process' then counter_name + ' ('+pc.instance_name+')'\n\t\t\t\t\t\twhen  pc.[object_name] = 'Processor' then counter_name + ' ('+pc.[object_name]+')'\n\t\t\t\t\telse null\n\t\t\t\t\tend  COLLATE SQL_Latin1_General_CP1_CI_AS\n\t\t,[value] = pc.cntr_value\nfrom dbo.dm_os_performance_counters_nonsql as pc with (nolock)\nwhere 1 = 1\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\n--and collection_time >= DATEADD(MINUTE,-120,getdate())\n--and pc.server_name = @server_name\nand\t(\t--(pc.[object_name] = 'Process' and counter_name like '!% % Time' ESCAPE '!' and pc.instance_name = 'sqlservr')\n\t\t--or\n\t\t(pc.[object_name] = 'Processor' and counter_name = '% Privileged Time')\n\t)\n--and counter_name like '!% Processor Time' ESCAPE '!'\norder by time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Per cpu - Processor Queue Length/Context Switches",
     "type": "graph",
     "description": "Number of threads waiting for CPU cycles,\nwhere < 12 per CPU is good/fair, < 8 is better,\n< 4 is best.\n\nNumber of execution contexts switched in\nthe last second, where >6000 is poor, <3000\nis good, and <1500 is excellent.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect \n\t\tdbo.local2utc(pc.collection_time) as time\n\t\t,metric = 'CPU - '+pc.counter_name+' ('+pc.[object_name]+')'\n\t\t,[value] = pc.cntr_value/si.cpu_count\nfrom dbo.dm_os_performance_counters_nonsql as pc with (nolock)\nouter apply ( select top 1 cpu_count from dbo.dm_os_sys_info as si where si.collection_time <= pc.collection_time) as si\nwhere 1 = 1\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\n--and collection_time >= DATEADD(MINUTE,-20,getdate())\nand\t(\t(pc.[object_name] = 'System' and counter_name = 'Processor Queue Length')\n\t\tor\n\t\t(pc.[object_name] = 'System' and counter_name = 'Context Switches/sec')\n\t)\n--and counter_name like '!% Processor Time' ESCAPE '!'\norder by time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Data Access Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:Access Methods",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, counter_name, cntr_value\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand pc.object_name = 'SQLServer:Access Methods'\r\nand pc.counter_name not in ('Index Searches/sec')\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo()) \r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:Access Methods",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, counter_name, cntr_value\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand pc.object_name = 'SQLServer:Access Methods'\r\nand pc.counter_name = 'Index Searches/sec'\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo()) \r\norder by collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Server: Memory Manager Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL Server: Memory Manager",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect\ttime = dbo.local2utc(pc.collection_time),\n\t\tmetric = pc.counter_name,\n\t\t[value] = pc.cntr_value\nfrom dbo.dm_os_performance_counters as pc\nwhere 1 = 1\n--and server_name = @server\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\nand (\t(pc.[object_name] = 'SQLServer:Memory Manager' and pc.counter_name in ('Granted Workspace Memory (KB)','Maximum Workspace Memory (KB)','Target Server Memory (KB)'))\n\t)\norder by pc.collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Memory Grants",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect\ttime = dbo.local2utc(pc.collection_time),\n\t\tmetric = pc.counter_name,\n\t\t[value] = pc.cntr_value\nfrom dbo.dm_os_performance_counters as pc\nwhere 1 = 1\n--and server_name = @server\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\nand (\t(pc.[object_name] = 'SQLServer:Memory Manager' and pc.counter_name in ('Memory Grants Outstanding','Memory Grants Pending'))\n\t)\norder by pc.collection_time\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logical Disk - Queue Length",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect  /* Load on Disk */\n\t\t[time] = dbo.local2utc(pc.collection_time),\n\t\tmetric = counter_name+' ('+pc.instance_name+')',\n\t\t[value] = pc.cntr_value\nfrom dbo.dm_os_performance_counters_nonsql as pc\nwhere 1 = 1\n--and server_name = @server\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\nand pc.[object_name] in ( 'LogicalDisk' )\nand pc.counter_name in ('Current Disk Queue Length')\nand NOT (pc.instance_name = '_Total' or pc.instance_name like 'Harddisk%')\norder by pc.collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Logical Disk - Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect [time] = dbo.local2utc(pc.collection_time),\n\t\tmetric = counter_name+' ('+pc.instance_name+')',\n\t\t[value] = pc.cntr_value\n--distinct object_name, counter_name, instance_name\nfrom dbo.dm_os_performance_counters_nonsql as pc\nwhere 1 = 1\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\nand pc.[object_name] in ( 'LogicalDisk' )\n--and pc.[object_name] in ( 'PhysicalDisk' )\nand pc.counter_name in ('Avg. Disk sec/Read','Avg. Disk sec/Write')\nand NOT (pc.instance_name = '_Total' or pc.instance_name like 'Harddisk%')\norder by pc.collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Logical Disk - Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect  /* Load on Disk */\n\t\t[time] = dbo.local2utc(pc.collection_time),\n\t\tmetric = counter_name+' ('+pc.instance_name+')',\n\t\t[value] = pc.cntr_value\n\t\t--distinct object_name, counter_name --,instance_name\nfrom dbo.dm_os_performance_counters_nonsql as pc\nwhere 1 = 1\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\nand pc.[object_name] in ( 'LogicalDisk' )\n--and pc.[object_name] in ( 'PhysicalDisk' )\n--and pc.counter_name in ('Current Disk Queue Length')\n--and pc.counter_name in ('% Disk Time','% Idle Time','% Disk Read Time','% Disk Write Time')\nand pc.counter_name in ('Disk Bytes/sec','Disk Write Bytes/sec','Disk Read Bytes/sec')\n--and pc.counter_name in ('Avg. Disk sec/Read','Avg. Disk sec/Write')\nand NOT (pc.instance_name = '_Total' or pc.instance_name like 'Harddisk%')\norder by pc.collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Physical Disk - Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect [time] = dbo.local2utc(pc.collection_time),\n\t\tmetric = counter_name+' ('+pc.instance_name+')',\n\t\t[value] = pc.cntr_value\n--distinct object_name, counter_name, instance_name\nfrom dbo.dm_os_performance_counters_nonsql as pc\nwhere 1 = 1\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\n--and pc.[object_name] in ( 'LogicalDisk' )\nand pc.[object_name] in ( 'PhysicalDisk' )\nand pc.counter_name in ('Avg. Disk sec/Read','Avg. Disk sec/Write')\nand NOT (pc.instance_name = '_Total' or pc.instance_name like 'Harddisk%')\norder by pc.collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Interface - Bytes Total/sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect  /* Load on Disk */\n\t\t[time] = dbo.local2utc(pc.collection_time),\n\t\tmetric = pc.instance_name,\n\t\t[value] = pc.cntr_value\nfrom dbo.dm_os_performance_counters_nonsql as pc\nwhere 1 = 1\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\nand pc.[object_name] in ( 'Network Interface' )\nand pc.counter_name in ('Bytes Total/sec')\norder by pc.collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL User Database Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:Databases - Log File Usage ( > 1GB)",
     "type": "graph",
     "description": "Monitor these counters to determine general benchmark levels set by your user databases and for tempdb.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\n;WITH T_Dbs AS (\n\tselect *\n\tfrom dbo.dm_os_performance_counters as pc\n\twhere 1 = 1\n\tand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\n\tand pc.[object_name] = 'SQLServer:Databases'\n\tand pc.counter_name in ('Log File(s) Used Size (KB)','Log File(s) Size (KB)')\n\t--and pc.counter_name = 'Percent Log Used'\n\tand instance_name not in ('_Total','master','model','mssqlsystemresource')\n\t--and pc.cntr_value/(1024.0*1024) > 1.0\n)\nselect [time] = dbo.local2utc(pc.collection_time),\n\t\t--pc.collection_time,\n\t\tmetric = case when counter_name = 'Log File(s) Size (KB)' then 'Total Size (KB) - '+QUOTENAME(pc.instance_name)\n\t\t\t\t\t\twhen counter_name = 'Log File(s) Used Size (KB)' then 'Used Size (KB) - '+QUOTENAME(pc.instance_name)\n\t\t\t\t\t\telse counter_name+' ('+pc.instance_name+')'\n\t\t\t\t\t\tend ,\n\t\t[value] = pc.cntr_value\nfrom T_Dbs as pc\nwhere pc.instance_name in (\tselect i.instance_name \n\t\t\t\t\t\t\tfrom T_Dbs as i \n\t\t\t\t\t\t\twhere i.counter_name = 'Log File(s) Size (KB)'\n\t\t\t\t\t\t\t\tand i.cntr_value/(1024.0*1024) > 1.0\n\t\t\t\t\t\t)\norder by collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Server SQL Statistics Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:SQL Statistics",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, counter_name, cntr_value\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand pc.object_name = 'SQLServer:SQL Statistics' --and counter_name not in ('Memory Grants Pending')\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\norder by collection_time asc;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Buffer Manager & Memory Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:Buffer Manager",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, counter_name, cntr_value\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand pc.object_name = 'SQLServer:Buffer Manager' and counter_name in ('Page lookups/sec','Page reads/sec','Page writes/sec','Readahead pages/sec')\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\norder by collection_time asc;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:Buffer Manager",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, counter_name, cntr_value\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand pc.object_name = 'SQLServer:Buffer Manager' and counter_name not in ('Page life expectancy','Database pages','Target pages')\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\norder by collection_time asc;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL “How is My Memory Being Used” Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:Buffer Manager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, counter_name as metric, cntr_value as [value]\r\n\t\t--distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\n--and pc.collection_time >= GETDATE()-1\r\nand pc.object_name = 'SQLServer:Memory Manager' \r\nand counter_name in ('Total Server Memory (KB)','Target Server Memory (KB)')\r\norder by pc.collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:Buffer Manager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, counter_name as metric, cntr_value as [value]\r\n\t\t--distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\n--and pc.collection_time >= GETDATE()-1\r\nand pc.object_name = 'SQLServer:Memory Manager' \r\nand counter_name in ('Stolen Server Memory (KB)','SQL Cache Memory (KB)','Free Memory (KB)')\r\norder by pc.collection_time asc;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Workload Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:SQL Statistics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\nSET QUOTED_IDENTIFIER OFF\nDECLARE @sql varchar(max) = \"\nselect dbo.local2utc(collection_time) as time, counter_name as metric, cntr_value as [value]\n\t\t--distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\nfrom dbo.dm_os_performance_counters as pc\nwhere 1 = 1\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\n--and pc.collection_time >= GETDATE()-1\nand pc.object_name = 'SQLServer:SQL Statistics' \nand counter_name in ('Batch Requests/sec','SQL Compilations/sec','SQL Re-Compilations/sec','SQL Attention rate')\norder by pc.collection_time;\n\"\nSET QUOTED_IDENTIFIER ON\nIF ('$server' = SERVERPROPERTY('ServerName'))\nBEGIN\n  EXEC (@sql);\nEND;\nELSE\nBEGIN\n  EXEC (@sql) AT [$server];\nEND;"
      }
     ]
    },
    {
     "title": "Number of Deadlocks/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, instance_name as metric, cntr_value as [value]\r\n\t\t  --distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\n--and pc.collection_time >= GETDATE()-1\r\nand pc.object_name like 'SQLServer:Locks'\r\nand pc.counter_name = 'Number of Deadlocks/sec'\r\norder by pc.collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:SQL Errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, instance_name as metric, cntr_value as [value]\r\n\t\t--distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\n--and pc.collection_time >= GETDATE()-1\r\nand pc.object_name = 'SQLServer:SQL Errors' \r\nand pc.instance_name <> '_Total'\r\norder by pc.collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQLServer:Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Longest Transaction Running Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, counter_name as metric, cntr_value as [value]\r\n\t\t  --distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\n--and pc.collection_time >= GETDATE()-1\r\nand pc.object_name like 'SQLServer:Transactions'\r\nand pc.counter_name in ('Longest Transaction Running Time')\r\norder by pc.collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "Free Space in tempdb (KB)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, counter_name as metric, cntr_value as [value]\r\n\t\t  --distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\n--and pc.collection_time >= GETDATE()-1\r\nand pc.object_name like 'SQLServer:Transactions'\r\nand pc.counter_name in ('Free Space in tempdb (KB)')\r\norder by pc.collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, counter_name as metric, cntr_value as [value]\r\n\t\t  --distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\n--and pc.collection_time >= GETDATE()-1\r\nand pc.object_name like 'SQLServer:Transactions'\r\nand pc.counter_name in ('Transactions')\r\norder by pc.collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "Version Store Size (KB)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, counter_name as metric, cntr_value as [value]\r\n\t\t  --distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\n--and pc.collection_time >= GETDATE()-1\r\nand pc.object_name like 'SQLServer:Transactions'\r\nand pc.counter_name in ('Version Store Size (KB)')\r\norder by pc.collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQLServer:General Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:General Statistics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, counter_name as metric, cntr_value as [value]\r\n\t\t  --distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\n--and pc.collection_time >= GETDATE()-1\r\nand (\tpc.object_name = 'SQLServer:General Statistics'\r\n\t\tand\t\r\n\t\t(\tpc.counter_name in ('User Connections','Logins/sec','Logouts/sec') )\r\n\t)\r\norder by pc.collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL Users & Locks Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLServer:Latches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, counter_name as metric, cntr_value as [value]\r\n\t\t--distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\n--and pc.collection_time >= GETDATE()-1\r\nand pc.object_name like 'SQLServer:Latches'\r\norder by pc.collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:Locks -> Lock Waits/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, instance_name as metric, cntr_value as [value]\r\n\t\t--distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\n--and pc.collection_time >= GETDATE()-1\r\nand pc.object_name like 'SQLServer:Locks'\r\nand pc.counter_name = 'Lock Waits/sec'\r\norder by pc.collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:Locks - Average Wait Time (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, instance_name as metric, cntr_value as [value]\r\n\t\t    --distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\n--and pc.collection_time >= GETDATE()-1\r\nand pc.object_name like 'SQLServer:Locks'\r\nand pc.counter_name = 'Average Wait Time (ms)'\r\norder by pc.collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    },
    {
     "title": "SQLServer:Locks - Lock Wait Time (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;\r\nSET QUOTED_IDENTIFIER OFF\r\nDECLARE @sql varchar(max) = \"\r\nselect dbo.local2utc(collection_time) as time, instance_name as metric, cntr_value as [value]\r\n\t\t    --distinct pc.object_name, pc.counter_name, pc.instance_name, pc.cntr_type\r\nfrom dbo.dm_os_performance_counters as pc\r\nwhere 1 = 1\r\nand collection_time BETWEEN dbo.utc2local($__timeFrom()) AND dbo.utc2local($__timeTo())\r\n--and pc.collection_time >= GETDATE()-1\r\nand pc.object_name like 'SQLServer:Locks'\r\nand pc.counter_name = 'Lock Wait Time (ms)'\r\norder by pc.collection_time;\r\n\"\r\nSET QUOTED_IDENTIFIER ON\r\nIF ('$server' = SERVERPROPERTY('ServerName'))\r\nBEGIN\r\n  EXEC (@sql);\r\nEND;\r\nELSE\r\nBEGIN\r\n  EXEC (@sql) AT [$server];\r\nEND;"
      }
     ]
    }
   ]
  }
 ]
}